#' Save TensorFlow Model
#' 
#' Saves a TensorFlow model with the goal of deploying and reusing across systems.
#' 
#' @param model A TensorFlow model. For instance, as generated by \code{linear_regressor()}.
#' @param path The destination path where the model will be saved.
#' @param spec The model specification, each model has a default specification;
#'   but it can be further defined specific functions like \code{tf_save_regressor_spec}.
#'   
#' @family save
#' @export
tf_save <- function(model, path, spec) {
  UseMethod("tf_save")
}

#' Create Save-Specification from Model
#' 
#' Creates default specification for a given model.
#' 
#' @param model A TensorFlow model. For instance, as generated by \code{linear_regressor()}.
#' 
#' @export
#' @family save
tf_save_spec_from_model <- function(model) {
  UseMethod("tf_save_spec_from_model")
}

#' @export
#' @family save
tf_save_spec_from_model.tf_estimator <- function(model) {
  feature_columns <- c(
    model$params$feature_columns,
    model$params$linear_feature_columns,
    model$params$dnn_feature_columns
  )
  
  list(
    feature_columns = model$params$feature_columns,
    weight_column = model$params$weight_column,
    label_key = "label"
  )
}

#' @export
#' @family save
tf_save.tf_estimator_regressor <- function(model, path, spec = tf_save_spec_from_model(model)) {
  input_spec <- do.call("regressor_parse_example_spec", spec)
  
  input_receiver <- tf$estimator$export$build_parsing_serving_input_receiver_fn(input_spec)
  
  export_savedmodel(model, 
                    export_dir_base = path,
                    serving_input_receiver_fn = input_receiver)
}

#' @export
#' @family save
tf_save.tf_estimator_classification <- function(model, path, spec = tf_save_spec_from_model(model)) {
  input_spec <- do.call("classification_parse_example_spec", spec)
  
  input_receiver <- tf$estimator$export$build_parsing_serving_input_receiver_fn(input_spec)
  
  export_savedmodel(model, 
                    export_dir_base = path,
                    serving_input_receiver_fn = input_receiver)
}
